SET NAMES 'utf8mb4';

DROP DATABASE IF EXISTS Psykodeck;
CREATE DATABASE Psykodeck ;
USE Psykodeck;

-- Tabla Insignias 
CREATE TABLE INSIGNIAS (
	ID_INSIGNIA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la Insignia',
    NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre de la Isignia',
    DESCRIPCION TEXT NULL COMMENT 'Descripción de la Insignia',
    CONSTRAINT PK_ID_INSIGNIA PRIMARY KEY (ID_INSIGNIA)
);

-- Tabla Usuarios
CREATE TABLE USUARIOS (
	ID_USUARIO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Usuario',
    NOMBRE VARCHAR(25) NOT NULL COMMENT 'Nombre del Usuario',
    CORREO VARCHAR(100) NOT NULL COMMENT 'Correo Electronico del Usuario',
    CONTR VARCHAR(30) NOT NULL COMMENT 'Contraseña del Usuario',
    SOULD ENUM ('AFTERLINE','REDLINE','BLACKLINE') NOT NULL COMMENT 'El Alma del Usuario',
    NIVEL VARCHAR(26) NOT NULL COMMENT 'Nivel del Usuario',
    EXPERIENCIA INT NOT NULL COMMENT 'Experiencia del Usuario',
    TIPO ENUM('JUGADOR', 'BOT') NOT NULL COMMENT 'Tipo de Jugador',
    ID_INSIGNIA INT NULL COMMENT 'Insignia que posee el Usuario',
    CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_ID_INSIGNIA FOREIGN KEY (ID_INSIGNIA) REFERENCES INSIGNIAS(ID_INSIGNIAS)
);

-- Tabla Cartas
CREATE TABLE CARTAS (
	ID_CARTA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la carta',
    NOMBRE VARCHAR(25) NOT NULL COMMENT 'Nombre de la carta',
    COSTE INT NOT NULL COMMENT 'Coste de la Carta (Psique)',
    TIPO ENUM('CRIATURA', 'EFECTO') NOT NULL COMMENT 'Tipo de Carta',
    CONSTRAINT PK_ID_CARTA PRIMARY KEY (ID_CARTA)
);

-- Tabla Carta de Efecto
CREATE TABLE EFECTO (
	ID_CARTA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la carta',
    NOMBRE VARCHAR(25) NOT NULL COMMENT 'Nombre de la carta',
    COSTE INT NOT NULL COMMENT 'Coste de la Carta (Psique)',
    TIPO ENUM('CRIATURA', 'EFECTO') NOT NULL COMMENT 'Tipo de Carta',
    CONSTRAINT PK_ID_CARTA PRIMARY KEY (ID_CARTA)
);

-- Tabla de los Tipos
CREATE TABLE TIPOS (
	ID_TIPO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la carta',
    NOMBRE VARCHAR(25) NOT NULL COMMENT 'Nombre del tipo',
    CONSTRAINT PK_ID_TIPO PRIMARY KEY (ID_TIPO)
);

-- Tabla de las Criaturas
CREATE TABLE CRIATURAS (
	ID_CRIATURA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de las criaturas',
    NOMBRE VARCHAR (25) NOT NULL COMMENT 'Nombre de las Criaturas',
    ATAQUE INT NOT NULL COMMENT 'Ataque de la Criatura',
    VIDA INT NOT NULL COMMENT 'Vida de la Criatura',
    VELOCIDAD INT NOT NULL COMMENT 'Velocidad de la Criatura',
    IMAGEN varchar(255) NOT NULL COMMENT 'Ruta de la Imagen de la Criatura',
    TIPO INT NULL COMMENT 'Tipo de la Carta',
    CARTA INT NULL COMMENT 'Numero de la Carta',
    CONSTRAINT PK_ID_CRIATURA PRIMARY KEY (ID_CRIATURA),
    CONSTRAINT FK_TIPO FOREIGN KEY (TIPO) REFERENCES TIPOS (ID_TIPO),
    CONSTRAINT FK_CARTA FOREIGN KEY (CARTA) REFERENCES CARTAS (ID_CARTA)
);

-- Tabla de los Escenarios
CREATE TABLE ESCENARIOS (
	ID_ESCENARIO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Escenario',
    NOMBRE VARCHAR(25) NOT NULL COMMENT 'Nombre del escenario',
    CONCEPTO TEXT NOT NULL COMMENT 'Concepto del escenario',
    IMAGEN VARCHAR(255) NOT NULL COMMENT 'Ruta de la Imagen del Escenario',
    CONSTRAINT PK_ID_ESCENARIO PRIMARY KEY (ID_ESCENARIO)
);

CREATE TABLE PARTIDA (
	ID_PARTIDA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la partida',
    TURNO INT NOT NULL COMMENT 'Turno de la Partida',
    USUARIO1 INT NULL COMMENT 'Jugador 1',
    USUARIO2 INT NULL COMMENT 'Jugador 2',
    ESCENARIO INT NOT NULL COMMENT 'Escenario de la Partida',
    CONSTRAINT PK_ID_PARTIDA PRIMARY KEY (ID_PARTIDA),
    CONSTRAINT FK_USUARIO1 FOREIGN KEY (USUARIO1) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_USUARIO2 FOREIGN KEY (USUARIO2) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_ESCENARIO FOREIGN KEY (ESCENARIO) REFERENCES ESCENARIOS (ID_ESCENARIO)
);





