SET NAMES 'utf8mb4';

DROP DATABASE IF EXISTS PSYKODECK;
CREATE DATABASE PSYKODECK CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE PSYKODECK;

-- 1. Tabla Insignias 
CREATE TABLE INSIGNIAS (
    ID_INSIGNIA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la Insignia',
    NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre de la Insignia',
    DESCRIPCION TEXT NULL COMMENT 'Descripción de la Insignia',
    CONSTRAINT PK_ID_INSIGNIA PRIMARY KEY (ID_INSIGNIA)
);

-- 2. Tabla Usuarios
CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Usuario',
    NOMBRE VARCHAR(25) NOT NULL COMMENT 'Nombre del Usuario',
    CORREO VARCHAR(100) NOT NULL COMMENT 'Correo Electrónico del Usuario',
    CONTR VARCHAR(255) NOT NULL COMMENT 'Contraseña del Usuario (Hash)',
    SOULD ENUM('AFTERLINE', 'REDLINE', 'BLACKLINE') NOT NULL COMMENT 'El Alma del Usuario',
    NIVEL INT NOT NULL DEFAULT 1 COMMENT 'Nivel del Usuario',
    EXPERIENCIA INT NOT NULL DEFAULT 0 COMMENT 'Experiencia del Usuario',
    TIPO ENUM('JUGADOR', 'BOT') NOT NULL DEFAULT 'JUGADOR' COMMENT 'Tipo de Jugador',
    ID_INSIGNIA INT NULL COMMENT 'Insignia que posee el Usuario',
    CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_ID_INSIGNIA FOREIGN KEY (ID_INSIGNIA) REFERENCES INSIGNIAS(ID_INSIGNIA) ON DELETE SET NULL
);

-- 3. Tabla Cartas (Catálogo General)
CREATE TABLE CARTAS (
    ID_CARTA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la carta',
    NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre de la carta',
    COSTE INT NOT NULL COMMENT 'Coste de la Carta (Psique)',
    TIPO ENUM('CRIATURA', 'EFECTO') NOT NULL COMMENT 'Tipo de Carta',
    CONSTRAINT PK_ID_CARTA PRIMARY KEY (ID_CARTA)
);

-- 4. Tabla de los Tipos / Facciones
CREATE TABLE TIPOS (
    ID_TIPO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Tipo',
    NOMBRE VARCHAR(25) NOT NULL COMMENT 'Nombre del tipo',
    CONSTRAINT PK_ID_TIPO PRIMARY KEY (ID_TIPO)
);

-- 5. Tabla de las Criaturas
CREATE TABLE CRIATURAS (
    ID_CRIATURA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la criatura',
    NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre de la Criatura',
    ATAQUE INT NOT NULL COMMENT 'Ataque de la Criatura',
    VIDA INT NOT NULL COMMENT 'Vida de la Criatura',
    VELOCIDAD INT NOT NULL COMMENT 'Velocidad de la Criatura',
    IMAGEN VARCHAR(255) NOT NULL COMMENT 'Ruta de la Imagen (512x512)',
    ID_TIPO INT NOT NULL COMMENT 'Tipo/Facción de la Criatura',
    ID_CARTA INT NOT NULL COMMENT 'Enlace a la Carta Base',
    CONSTRAINT PK_ID_CRIATURA PRIMARY KEY (ID_CRIATURA),
    CONSTRAINT FK_CRIATURA_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPOS(ID_TIPO),
    CONSTRAINT FK_CRIATURA_CARTA FOREIGN KEY (ID_CARTA) REFERENCES CARTAS(ID_CARTA) ON DELETE CASCADE
);

-- 6. Tabla Efecto (Hechizos/Habilidades)
CREATE TABLE EFECTO (
    ID_EFECTO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del efecto',
    NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre del Efecto',
    DESCRIPCION TEXT NOT NULL COMMENT 'Regla o habilidad que ejecuta',
    IMAGEN VARCHAR(255) NULL COMMENT 'Ruta de la Imagen (512x512)',
    ID_CARTA INT NOT NULL COMMENT 'Enlace a la Carta Base',
    CONSTRAINT PK_ID_EFECTO PRIMARY KEY (ID_EFECTO),
    CONSTRAINT FK_EFECTO_CARTA FOREIGN KEY (ID_CARTA) REFERENCES CARTAS(ID_CARTA) ON DELETE CASCADE
);

-- 7. Tabla Escenarios
CREATE TABLE ESCENARIOS (
    ID_ESCENARIO INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Escenario',
    NOMBRE VARCHAR(50) NOT NULL COMMENT 'Nombre del escenario',
    CONCEPTO TEXT NOT NULL COMMENT 'Concepto del escenario',
    IMAGEN VARCHAR(255) NOT NULL COMMENT 'Ruta del Fondo (1920x1080)',
    CONSTRAINT PK_ID_ESCENARIO PRIMARY KEY (ID_ESCENARIO)
);

-- 8. Tabla Partida
CREATE TABLE PARTIDA (
    ID_PARTIDA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la partida',
    TURNO INT NOT NULL DEFAULT 1 COMMENT 'Turno actual de la Partida',
    USUARIO1 INT NOT NULL COMMENT 'Jugador Humano',
    USUARIO2 INT NOT NULL COMMENT 'Jugador Bot/IA',
    ID_ESCENARIO INT NOT NULL COMMENT 'Escenario Activo',
    CONSTRAINT PK_ID_PARTIDA PRIMARY KEY (ID_PARTIDA),
    CONSTRAINT FK_PARTIDA_USUARIO1 FOREIGN KEY (USUARIO1) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PARTIDA_USUARIO2 FOREIGN KEY (USUARIO2) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PARTIDA_ESCENARIO FOREIGN KEY (ID_ESCENARIO) REFERENCES ESCENARIOS(ID_ESCENARIO)
);

-- 9. Tabla Instancia (Mano/Mazo/Tablero)
CREATE TABLE INSTANCIA (
    ID_INSTANCIA INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la carta en juego',
    ID_PARTIDA INT NOT NULL COMMENT 'Partida a la que pertenece',
    ID_USUARIO INT NOT NULL COMMENT 'Propietario de la carta',
    ID_CARTA INT NOT NULL COMMENT 'Carta referenciada',
    ESTADO ENUM('MAZO', 'MANO', 'TABLERO', 'CEMENTERIO') NOT NULL DEFAULT 'MAZO',
    CONSTRAINT PK_ID_INSTANCIA PRIMARY KEY (ID_INSTANCIA),
    CONSTRAINT FK_INSTANCIA_PARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDA(ID_PARTIDA) ON DELETE CASCADE,
    CONSTRAINT FK_INSTANCIA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_INSTANCIA_CARTA FOREIGN KEY (ID_CARTA) REFERENCES CARTAS(ID_CARTA)
);





